server:
  port: 8086

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:h2:mem:trackingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

booking:
  service:
    url: http://booking-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
